# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39b672e1aab934488877c96616c0aa56e71345c441b559192c714926ea5429a75d71ab18e3a762fd8df8d366822c40408f3a3356f08629756f7822dffa7e403

test:
  secret_key_base: 0fa34da7eb7044e4f05cda6c0462df042b0813ec683c65298f42fbb09f237c6e7d360c9c587696b430078a00ee344f636269abf669852841680c390c74087aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
